### ISSUE TITLE
Replace `pexpect` with `subprocess`

### ISSUE THREAD

**Issue by markyfsun** [amosjyng/langchain-contrib#28]
my platform: macOS (Intel)

When I was running `zamm` and approving a terminal process, it stuck for several seconds then raised
```
│ /Users/markyfsun/.conda/envs/auto_weekly/lib/python3.10/site-packages/langchain_contrib/tools/te │
│ rminal/terminal.py:84 in _get_raw_shell_update_uncached                                          │
│                                                                                                  │
│    81 │   │   │   │   results += latest_output                                                   │
│    82 │   │   │   │   time.sleep(0.1)                                                            │
│    83 │   │   except pexpect.TIMEOUT as e:                                                       │
│ ❱  84 │   │   │   raise UnknownResult(                                                           │
│    85 │   │   │   │   "Terminal output does not have initial prompt of: "                        │
│    86 │   │   │   │   f"'{self.bash_prompt}':\n\n{results}"                                      │
│    87 │   │   │   ) from e                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnknownResult: Terminal output does not have initial prompt of: '
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
[1m[?1034hzamm$ ':

python3 hello.py
Hello world
Bye
zamm$ 
```

I assume that `pexpect` here expects `$` as the start flag and the EOF flag, however my terminal wrote something else to the output, so the match could not be found.

I wonder if you can use `subprocess.getoutput` here to execute `bash` command, since you only need to get the output of the command?

**Comment by markyfsun** [comment]
I found another way to fix this: drop the output after spawning, enter an empty input, then use the output as `bash_prompt`. This could avoid noise from the initialization of bash.

**Comment by amosjyng** [comment]
Ooof, I am so sorry, I just saw this! It seems my Github notifications still aren't working right yet :(

I made some changes to get the fix to work on WSL Ubuntu. Can you check to see if it still works on the Mac?

Regarding using `subprocess`, it didn't seem like I could maintain shell state unless I started a shell as a subprocess, at which point [doing a non-blocking read seems convoluted](https://stackoverflow.com/questions/375427/a-non-blocking-read-on-a-subprocess-pipe-in-python). I went with pexpect for that reason.
